"""empty message

Revision ID: 2fdaf1b743ea
Revises: 7c3e992cb60a
Create Date: 2020-08-04 22:48:50.577329

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '2fdaf1b743ea'
down_revision = '7c3e992cb60a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stake', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stake', 'amount',
               existing_type=sa.Numeric(precision=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
