"""empty message

Revision ID: 7c3e992cb60a
Revises: 279403874592
Create Date: 2020-08-04 19:11:27.826063

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c3e992cb60a'
down_revision = '279403874592'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant',
                  sa.Column('status', sa.Enum('pending', 'active', 'inactive', name='participantstatusenum'),
                            nullable=False))
    op.drop_constraint('participant_status_uuid_fkey', 'participant', type_='foreignkey')
    op.create_unique_constraint(None, 'participant_status', ['name'])
    op.create_foreign_key(None, 'participant', 'participant_status', ['status'], ['name'])
    op.drop_column('participant', 'status_uuid')
    op.drop_constraint('participant_status_uuid_key', 'participant_status', type_='unique')
    op.drop_column('participant_status', 'id')
    op.drop_column('participant_status', 'uuid')
    op.add_column('wager',
                  sa.Column('status', sa.Enum('pending', 'active', 'inactive', name='wagerstatusenum'), nullable=True))
    op.drop_constraint('wager_status_uuid_fkey', 'wager', type_='foreignkey')
    op.create_unique_constraint(None, 'wager_status', ['name'])
    op.create_foreign_key(None, 'wager', 'wager_status', ['status'], ['name'])
    op.drop_column('wager', 'status_uuid')
    op.drop_constraint('wager_status_uuid_key', 'wager_status', type_='unique')
    op.drop_column('wager_status', 'id')
    op.drop_column('wager_status', 'uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wager_status', sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.add_column('wager_status',
                  sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('wager_status_id_seq'::regclass)"),
                            autoincrement=True, nullable=False))
    op.drop_constraint(None, 'wager_status', type_='unique')
    op.create_unique_constraint('wager_status_uuid_key', 'wager_status', ['uuid'])
    op.add_column('wager', sa.Column('status_uuid', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'wager', type_='foreignkey')
    op.create_foreign_key('wager_status_uuid_fkey', 'wager', 'wager_status', ['status_uuid'], ['uuid'])
    op.drop_column('wager', 'status')
    op.add_column('participant_status', sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.add_column('participant_status', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'participant_status', type_='unique')
    op.create_unique_constraint('participant_status_uuid_key', 'participant_status', ['uuid'])
    op.add_column('participant', sa.Column('status_uuid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.create_foreign_key('participant_status_uuid_fkey', 'participant', 'participant_status', ['status_uuid'],
                          ['uuid'])
    op.drop_column('participant', 'status')
    # ### end Alembic commands ###
