"""empty message

Revision ID: ccc72616e649
Revises: 2fdaf1b743ea
Create Date: 2020-08-04 23:08:17.704613

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'ccc72616e649'
down_revision = '2fdaf1b743ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stake', 'amount',
               existing_type=sa.NUMERIC(precision=2, scale=0),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stake', 'amount',
               existing_type=sa.String(),
               type_=sa.NUMERIC(precision=2, scale=0),
               existing_nullable=True)
    # ### end Alembic commands ###
