"""empty message

Revision ID: 8ef81caa6a16
Revises: b4d2c8d8e2cf
Create Date: 2020-08-22 18:34:02.081037

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ef81caa6a16'
down_revision = 'b4d2c8d8e2cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wager', 'owner_uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wager', sa.Column('owner_uuid', postgresql.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
