"""empty message

Revision ID: b4d2c8d8e2cf
Revises: b36620e19b25
Create Date: 2020-08-07 18:57:53.795140

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b4d2c8d8e2cf'
down_revision = 'b36620e19b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contest', 'id')
    op.drop_column('participant', 'id')
    op.create_unique_constraint(None, 'participant_status', ['name'])
    op.drop_column('party', 'id')
    op.drop_column('stake', 'id')
    op.drop_column('wager', 'id')
    op.create_unique_constraint(None, 'wager_status', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wager_status', type_='unique')
    op.add_column('wager', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('wager_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.add_column('stake', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('party', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'participant_status', type_='unique')
    op.add_column('participant', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('participant_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.add_column('contest', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
